=== wanderingivan/ecommerce-example/src/test/resources/test.dtd
<!ELEMENT dataset (
    users*,
    products*,
    featured+,
    carts+,
    orders+,
    reviews*,
    carts_products*,
    orders_products*,
	chats*,
	chat_messages*,	
	chats_join_table*,
    tasks*,
    authorities?
)>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id CDATA #IMPLIED
    username CDATA #REQUIRED
    address CDATA #REQUIRED
    email CDATA #REQUIRED
    password CDATA #REQUIRED
    enabled CDATA #REQUIRED
    details CDATA #IMPLIED
    imagePath CDATA #IMPLIED
    locked CDATA #IMPLIED
    createdOn CDATA #IMPLIED
>

<!ELEMENT products EMPTY>
<!ATTLIST products 
    product_id CDATA #IMPLIED
    name CDATA #REQUIRED
    user_id CDATA #REQUIRED
    category CDATA #REQUIRED
    description CDATA #REQUIRED
    imagePath CDATA #REQUIRED
    created CDATA #IMPLIED
    hits CDATA #IMPLIED
    sold CDATA #IMPLIED
    sale CDATA #IMPLIED
    featured CDATA #IMPLIED
    price CDATA #REQUIRED
>
<!ELEMENT featured EMPTY>
<!ATTLIST featured 
	product_id CDATA #REQUIRED
	added CDATA #IMPLIED
>
<!ELEMENT details EMPTY>
<!ATTLIST details 
	detail_id CDATA #IMPLIED
	message CDATA #REQUIRED
	product_id CDATA #REQUIRED
>

<!ELEMENT reviews EMPTY>
<!ATTLIST reviews 
	review_id CDATA #IMPLIED
	message CDATA #REQUIRED
	user_id CDATA #REQUIRED
	product_id CDATA #REQUIRED
>

<!ELEMENT groups EMPTY>
<!ATTLIST groups 
	id CDATA #IMPLIED
	group_name CDATA #REQUIRED
>

<!ELEMENT group_members EMPTY>
<!ATTLIST group_members 
	id CDATA #IMPLIED
	username CDATA #REQUIRED
	group_id CDATA #REQUIRED
>

<!ELEMENT group_authorities EMPTY>
<!ATTLIST group_authorities 
	group_id CDATA #REQUIRED
	authority CDATA #REQUIRED
>

<!ELEMENT carts EMPTY>
<!ATTLIST carts
	cart_id CDATA #IMPLIED
	user_id CDATA #REQUIRED

>

<!ELEMENT orders EMPTY>
<!ATTLIST orders
	order_id CDATA #IMPLIED
	user_id CDATA #REQUIRED
	sold CDATA #REQUIRED
	sent CDATA #IMPLIED
	address CDATA #IMPLIED
>

<!ELEMENT orders_products EMPTY>
<!ATTLIST orders_products
	order_id CDATA #REQUIRED 
	product_id CDATA #REQUIRED
>

<!ELEMENT carts_products EMPTY>
<!ATTLIST carts_products
	cart_id CDATA #REQUIRED 
	product_id CDATA #REQUIRED
>


<!ELEMENT chats_join_table EMPTY>
<!ATTLIST chats_join_table
	chat_id CDATA #REQUIRED
	user_id CDATA #REQUIRED
>

<!ELEMENT chat_messages EMPTY>
<!ATTLIST chat_messages
	message_id CDATA #IMPLIED
	message CDATA #REQUIRED
	sent CDATA #IMPLIED
	chat_id CDATA #REQUIRED
	sender_id CDATA #REQUIRED
>

<!ELEMENT chats EMPTY>
<!ATTLIST chats
	chat_id CDATA #IMPLIED
	lastUpdate CDATA #IMPLIED
>

<!ELEMENT tasks EMPTY>
<!ATTLIST tasks
	task_id CDATA #IMPLIED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	assigner CDATA #REQUIRED
	assignee CDATA #REQUIRED
>

<!ELEMENT authorities EMPTY>
<!ATTLIST authorities
	username CDATA #REQUIRED 
	authority CDATA #REQUIRED 
>

=== wanderingivan/ecommerce-example/src/test/resources/DbTestDataSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset PUBLIC "//UNKNOWN/" "test.dtd">

<dataset>
	<users user_id="1" username="username1" email="some@email" password="Bar" enabled="1" locked="1" imagePath="350x350ProfilePic.png" details="test description1" address="test address" createdOn="2016-09-30 00:00:01"/>
	<users user_id="2" username="username2" email="some@email1" password="Bar" enabled="1" locked="1" imagePath="350x350ProfilePic.png" details="Placeholder Description" address="address" createdOn="2016-09-30 00:00:01"/>
	<users user_id="3" username="username3" email="some@email2" password="Bar" enabled="1" locked="1" imagePath="350x350ProfilePic.png" details="Placeholder Description" address="address" createdOn="2016-09-30 00:00:01"/>
	<users user_id="4" username="username4" email="some@email3" password="Bar" enabled="1" locked="1" imagePath="350x350ProfilePic.png" details="Placeholder Description" address="address" createdOn="2016-09-30 00:00:01"/>
	<users user_id="5" username="username5" email="some@email4"  password="Bar" enabled="1" locked="1" imagePath="350x350ProfilePic.png" details="Placeholder Description" address="address" createdOn="2016-09-30 00:00:01"/>

	<products product_id="1" name="product1" user_id="1" category="cat" hits="1" sold="1" featured="1" imagePath="product.png" description="description" price="10.30" sale="1" created="2016-09-30 00:00:10"/>
	<products product_id="2" name="product2" user_id="1" category="cat" hits="2" sold="2" featured="1" imagePath="product.png" description="description" price="10.30" sale="0" created="2016-09-30 00:00:10"/>
	<products product_id="3" name="product3" user_id="1" category="cat" hits="3" sold="2" featured="1" imagePath="product.png" description="description" price="10.30" sale="1" created="2016-09-30 00:00:10"/>
	<products product_id="4" name="product4" user_id="2" category="cat" hits="4" sold="3" featured="1" imagePath="product.png" description="description" price="10.30" sale="1" created="2016-09-30 00:00:10"/>
	<products product_id="5" name="product5" user_id="3" category="cat" hits="5" sold="4" featured="0" imagePath="product.png" description="description" price="10.30" sale="0" created="2016-09-30 00:00:10"/>
	<products product_id="6" name="product6" user_id="3" category="cat" hits="6" sold="5" featured="0" imagePath="product.png" description="description" price="10.30" sale="0" created="2016-09-30 00:00:10"/>
	<products product_id="7" name="product7" user_id="2" category="cat" hits="7" sold="6" featured="0" imagePath="product.png" description="description" price="10.30" sale="1" created="2016-09-30 00:00:10"/>
	<products product_id="8" name="product8" user_id="2" category="cat2" hits="8" sold="6" featured="0" imagePath="product.png" description="description" price="10.30" sale="1" created="2016-09-30 00:00:10"/>
	<products product_id="9" name="product9" user_id="1" category="cat2" hits="9" sold="6" featured="0" imagePath="product.png" description="description" price="10.30" sale="0" created="2016-09-30 00:00:10"/>
	<products product_id="10" name="product10" user_id="1" category="cat" hits="3" sold="4" featured="0" imagePath="product.png" description="description" price="10.30" sale="1" created="2016-09-30 00:00:10"/>

	<featured product_id="1" added="2016-09-30 00:00:10"/>
	<featured product_id="2" added="2016-09-30 00:00:10"/>
	<featured product_id="3" added="2016-09-30 00:00:10"/>
	<featured product_id="4" added="2016-09-30 00:00:10"/>

    <carts user_id="1" cart_id="1"/>
    <carts user_id="2" cart_id="2"/>
    <carts user_id="3" cart_id="3"/>
    <orders order_id="1" user_id="1" address="address" sent="1" sold="2017-02-02"/>
    <orders order_id="2" user_id="1" address="add" sent="1" sold="2017-03-01"/>
	<reviews review_id="1" message="mes" user_id="1" product_id="3"/>
	<reviews review_id="2" message="mes" user_id="2" product_id="3"/>
    <carts_products product_id="2" cart_id="1"/>
    <carts_products product_id="2" cart_id="1"/>
    <carts_products product_id="3" cart_id="1"/>
    <orders_products product_id="1" order_id="1"/>
    <orders_products product_id="3" order_id="1"/>
    <orders_products product_id="3" order_id="1"/>
    <orders_products product_id="1" order_id="2"/>
    <orders_products product_id="1" order_id="2"/>
    <orders_products product_id="1" order_id="2"/>
    <orders_products product_id="1" order_id="2"/>
	<chats chat_id="5" lastUpdate="2016-09-31 00:00:06"/>
	<chats chat_id="6" lastUpdate="2016-09-31 00:00:10"/>
	<chats chat_id="7" lastUpdate="2016-09-31 00:00:10"/>
	<chat_messages sender_id="1" chat_id="5" message="msg3" sent="2016-09-31 00:00:01"/>
	<chat_messages sender_id="2" chat_id="5" message="msg4" sent="2016-09-31 00:00:02"/>
	<chat_messages sender_id="1" chat_id="5" message="msg5" sent="2016-09-31 00:00:03"/>
	<chat_messages sender_id="1" chat_id="5" message="msg6" sent="2016-09-31 00:00:04"/>
	<chat_messages sender_id="1" chat_id="5" message="msg7" sent="2016-09-31 00:00:09"/>
	<chat_messages sender_id="2" chat_id="5" message="msg8" sent="2016-09-31 00:00:06"/>
	<chat_messages sender_id="1" chat_id="5" message="msg9" sent="2016-09-31 00:00:07"/>
	<chat_messages sender_id="1" chat_id="6" message="msg1" sent="2016-09-31 00:00:07"/>
	<chat_messages sender_id="3" chat_id="6" message="msg2" sent="2016-09-31 00:00:08"/>
	<chat_messages sender_id="1" chat_id="6" message="msg3" sent="2016-09-31 00:00:09"/>
	<chat_messages sender_id="3" chat_id="6" message="msg4" sent="2016-09-31 00:00:10"/>
	<chat_messages sender_id="3" chat_id="7" message="msg9" sent="2016-09-31 00:00:09"/>
	<chat_messages sender_id="2" chat_id="7" message="msg7" sent="2016-09-31 00:00:10"/>
	<chats_join_table user_id="1" chat_id="5"/>
	<chats_join_table user_id="2" chat_id="5"/>	
	<chats_join_table user_id="1" chat_id="6"/>
	<chats_join_table user_id="3" chat_id="6"/>
	<chats_join_table user_id="3" chat_id="7"/>
	<chats_join_table user_id="2" chat_id="7"/>
    <tasks task_id="1" assigner="username2" name="testTask1" description="test description" assignee="username1"/>
    <tasks task_id="2" assigner="username2" name="testTask2" description="test description" assignee="username3"/>
    <authorities username="username1" authority="ROLE_USER"/>
</dataset>
